#!/bin/sh

COMMAND=$1
FILE=$2

if [ -z $FILE ]; then
	FILE="development.sqlite3"
else
	FILE=$(ls ../db/$FILE*)
fi

if [ $COMMAND = "-r" ] && [ -r "../db/$FILE" ] && [ $FILE ]; then
	echo "Removing $FILE"
	rm -f ../db/$FILE
	echo "Creating $FILE"
	cd ../db/
	sqlite3 $FILE ""
	chmod o+w $FILE
fi

if [ $COMMAND = "-c" ]; then
	cd ../db/
	sqlite3 $FILE
fi

if [ $COMMAND = "-h" ]; then
	echo "\nusage: ./db [command] [database]\n\ncommand:\n -r : Drop and re-create\n -c : Enter sqlite3 console\n\ndatabase:\n Partials ('dev','test', 'prod') acceptable or provide full name. Database must exist in ../db/\n"

else
	echo "Done"
fi
